graph TD
    %% Main sections from controller_1
    controller_1[controller_1.ini: [controller_1]]
    controller_1_ota[controller_1.ini: [controller_1_ota]]
    env_ota_initial[controller_1.ini: [env:controller_1_ota_initial]]
    env_ota_followup[controller_1.ini: [env:controller_1_ota_followup]]
    env_micro_ros_test[controller_1.ini: [env:controller_1_micro_ros_test]]

    %% External dependencies
    esp32_p4_base[common.ini: [esp32_p4_base]]
    ethernet_ota_initial[ethernet_ota_initial.ini: [ethernet_ota_initial]]
    ethernet_ota_followup[ethernet_ota_followup.ini: [ethernet_ota_followup]]
    micro_ros_test[micro_ros_test.ini: [micro_ros_test]]

    %% Relationships
    controller_1_ota --> controller_1

    env_ota_initial --> esp32_p4_base
    env_ota_initial --> ethernet_ota_initial
    env_ota_initial --> controller_1

    env_ota_followup --> esp32_p4_base
    env_ota_followup --> ethernet_ota_followup
    env_ota_followup --> controller_1_ota

    env_micro_ros_test --> esp32_p4_base
    env_micro_ros_test --> micro_ros_test
    env_micro_ros_test --> controller_1_ota